allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

overrides:
  baseline-browser-mapping@>=2.0.0 <2.11.0: '>=2.11.0'
  browserslist@<=4.28.6: '>=4.28.7'
  esbuild: ^0.28.1
  nanoid@<3.3.18: '>=3.3.18'
  postcss@<=8.5.17: '>=8.5.18'
  sharp@<0.35.5: '>=0.35.5'
  source-map-js@<1.2.2: '>=1.2.2'
  undici: ^7.29.1
